# System
gpu_num: 1

# Model
train_serial: 'DeepLabV3Plus_timm-regnetx-064_imagenet_logsoftmax_b16_stride8_focalLoss_clahe_delNoise' # ex) '20221012_174254'

# Data
batch_size: 60
num_workers: 12

# Logging
verbose: false
